version: 2
updates:
  # Frontend
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
  # Backend
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
